title: "Delirium"

defaults:
  -
    scope:
      path: "_posts/"
      type: "posts"
    values:
      layout: "posts"
      permalink: "/blog/:title/"

collections:
  authors:
    output: true

url: "{{site.baseurl}}"

plugins:
  - jekyll-feed
  - jekyll-sitemap


feed:
  icon: "assets/images/favicon.svg"
  logo: "assets/images/favicon.svg"