environment: production
title: "Delirium"

defaults:
  -
    scope:
      path: "_posts/"
      type: "posts"
    values:
      layout: "posts"
      permalink: "/blog/:title"
      thumb: 
        src: "https://state-of-delirium.github.io/assets/images/thumb-missing.webp"
        height: "500"
        width: "500"

collections:
  authors:
    output: true

url: "state-of-delirium.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-minifier

feed:
  icon: "state-of-delirium.github.io/assets/images/favicon.svg"
  logo: "state-of-delirium.github.io/assets/images/favicon.svg"

target-blank:
  rel: external

sass:
  style: compressed

jekyll-minifier:
  exclude: "feed.xml"
  exclude: "*.css"