title: "Delirium"

defaults:
  -
    scope:
      path: "_posts/"
      type: "posts"
    values:
      layout: "posts"
      permalink: "/blog/:title"
      thumb: "https://state-of-delirium.github.io/assets/images/blog-empty.svg"

collections:
  authors:
    output: true

url: "state-of-delirium.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-target-blank

feed:
  icon: "state-of-delirium.github.io/assets/images/favicon.svg"
  logo: "state-of-delirium.github.io/assets/images/favicon.svg"

target-blank:
  rel: external

sass:
  style: compressed